# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    # Build job
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                language: [ 'cpp' ]
                # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
                # Learn more:
                # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

        steps:
        - uses: actions/checkout@v2

        # Install dependencies for building
        - name: Install Deps
          run: .github/install_dependencies.sh

        # Initialize code analyzer
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v1
          with:
            languages: ${{ matrix.language }}

        # Build step
        - name: Build
          run: |
              CC=gcc-10 CXX=g++-10 meson build
              cd build
              ninja tests

        # Test step
        - name: Test
          run: ./build/tests

        # Run analyser
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v1

    # Dockerizer job
    docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit || true
        - run: docker build . -t mysummerjob --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit
        - run: |
            docker tag mysummerjob docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit
            docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit || true
        - run: docker run -v $PWD:/app mysummerjob
